
spring.datasource.username: root
spring.datasource.password: Aa123456
spring.datasource.url: jdbc:mysql://192.168.1.18:3306/rbac?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


